baseurl: "/Financial-inclusion-toolkit"
plugins:
    - jekyll-seo-tag
gems:
- jekyll-email-protect

exclude:
  - README.md
  - Tutorials/
  - markdown_styling.md
  - vendor
  - CNAME
  - README.md
  - node_modules
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - packages
  - bin